build.gradle.kts, src/main/java/org/openrewrite/gradle/ExamplesExtractor.java, src/main/java/org/openrewrite/gradle/RecipeExamplesTask.java, src/test/java/org/openrewrite/gradle/ExamplesExtractorTest.java
Update examples extractor to support 
1. multiple sources
2. file path
Here is an example of an extracted example :
```yaml
type: specs.openrewrite.org/v1beta/example
recipeName: org.openrewrite.java.migrate.UpgradeToJava17
examples:
- description: ""
sources:
- before: |
<project>
<modelVersion>4.0.0</modelVersion>
<properties>
<java.version>1.8</java.version>
<maven.compiler.source>1.8</maven.compiler.source>
<maven.compiler.target>1.8</maven.compiler.target>
</properties>
<groupId>com.mycompany.app</groupId>
<artifactId>my-app</artifactId>
<version>1</version>
</project>
after: |
<project>
<modelVersion>4.0.0</modelVersion>
<properties>
<java.version>17</java.version>
<maven.compiler.source>17</maven.compiler.source>
<maven.compiler.target>17</maven.compiler.target>
</properties> …
```
=> Update examples extractor to support multiple sources and path in an example

src/main/java/org/openrewrite/gradle/RewriteJavaPlugin.java
Signed-off-by: Jonathan Leitschuh <Jonathan.Leitschuh@gmail.com>
=> Fix Test.setMaxParallelForks not being applied

suppressions.xml
Adding suppressions.xml for dependency-check task
The dependency check task fails without this file present.
=> fix: add missing suppressions.xml

build.gradle.kts, suppressions.xml
Updated outdated dependencies that have known vulnerabilities
Addressing https://github.com/moderneinc/dependency-vulnerability-reports/issues/606
Verify license plugin still functions with dependency constraints. I tested locally but be good for another to test.
@timtebeek
=> chore: updates to address vulnernability report from 01-03-2024

suppressions.xml
re: https://github.com/moderneinc/dependency-vulnerability-reports/issues/615
=> chore: update suppressions 01222024112454

suppressions.xml
re: https://github.com/moderneinc/dependency-vulnerability-reports/issues/618
=> chore: update suppressions for 01302024154734

suppressions.xml
Related to: https://github.com/moderneinc/dependency-vulnerability-reports/issues/622
=> chore: update suppressions for 01-31-2024 report

suppressions.xml
re: https://github.com/moderneinc/dependency-vulnerability-reports/issues/627
=> chore: update supression dates 02142024115752

build.gradle.kts, suppressions.xml
resolved latest version of commons-compress
=> chore: update suppression & resolve latest commons-compress

suppressions.xml
re: https://github.com/moderneinc/dependency-vulnerability-reports/issues/639
=> chore: update suppressions for 03182024135144

suppressions.xml
related: https://github.com/moderneinc/dependency-vulnerability-reports/issues/648
=> chore: update suppressions for 04102024155730

suppressions.xml
=> chore: add suppression CVE-2024-29857

suppressions.xml
re https://github.com/moderneinc/dependency-vulnerability-reports/issues/684
=> chore: update suppressions 06182024225713

suppressions.xml
related to:
- https://github.com/moderneinc/dependency-vulnerability-reports/issues/697
=> chore(suppressions): update range and revise cve

suppressions.xml
- related to: https://github.com/moderneinc/dependency-vulnerability-reports/issues/704, https://github.com/moderneinc/dependency-vulnerability-reports/issues/703
=> chore(suppressions): Update range for bcprov suppression

build.gradle.kts, src/main/java/org/openrewrite/gradle/RewriteDependencyCheckPlugin.java, suppressions.xml
re: https://github.com/moderneinc/dependency-vulnerability-reports/issues/709
=> chore: update dep check config and suppressions

suppressions.xml
Related to: https://github.com/moderneinc/dependency-vulnerability-reports/issues/724
=> chore: update suppressions for 2024-08-21 - OpenRewrite dependency vulnerability report

src/main/resources/suppressions.xml
- related to https://github.com/moderneinc/dependency-vulnerability-reports/issues/727
-
=> chore: update woodstox-core and gradle-core-api vulnerability suppresions

src/main/resources/suppressions.xml
re: https://github.com/moderneinc/dependency-vulnerability-reports/issues/736
=> chore: update suppressions 09122024091729

src/main/resources/suppressions.xml
Related to: https://github.com/moderneinc/dependency-vulnerability-reports/issues/741
=> update suppressions for 09-25-2024 vulnerability report

src/main/resources/suppressions.xml
- related to: https://github.com/moderneinc/dependency-vulnerability-reports/issues/781
=> chore: Update OWASP suppressions

src/main/resources/suppressions.xml
Updating the log4J suppression to contain the following CVEs
- CVE-2022-23302
- CVE-2023-26464
- CVE-2021-4104
=> Updating the suppressions

src/main/resources/suppressions.xml, suppressions.xml
re: https://github.com/moderneinc/dependency-vulnerability-reports/issues/796
=> chore: update suppressions for 2025-01-15 report

build.gradle.kts, gradle/wrapper/gradle-wrapper.properties
This allows us to adopt type tables; (not added here yet)
=> Bump OpenRewrite version to v8.44.2

src/main/resources/suppressions.xml
re: https://github.com/moderneinc/dependency-vulnerability-reports/issues/806
=> chore: add known suppression 02052025125002

build.gradle.kts, src/main/java/org/openrewrite/gradle/RewriteJavaPlugin.java, src/test/java/org/openrewrite/gradle/RecipeDependenciesTypeTableTaskTest.java
Following
- https://github.com/openrewrite/rewrite/pull/5013
- https://github.com/openrewrite/rewrite/pull/5025
- https://github.com/openrewrite/lombok
=> Adopt `org.openrewrite.tools:lombok` until their next release

build.gradle.kts
=> pin com.netflix.nebula.release

build.gradle.kts, suppressions.xml
Related to: https://github.com/moderneinc/dependency-vulnerability-reports/issues/820 
Updating dependencycheck versin per this issue: https://github.com/dependency-check/DependencyCheck/issues/7463
=> update suppressions and owasp.dependencycheck version. 

src/main/resources/suppressions.xml
re: [2025-03-05 - Moderne dependency vulnerability report](https://github.com/moderneinc/dependency-vulnerability-reports/issues/821)
re: [2025-03-05 - OpenRewrite dependency vulnerability report](https://github.com/moderneinc/dependency-vulnerability-reports/issues/820)
[vulnerability](https://github.com/moderneinc/dependency-vulnerability-reports/issues?q=is%3Aissue%20state%3Aopen%20label%3Avulnerability)
=> chore: update suppression for 03-05-2025 report

suppressions.xml
Add suppression for okio vulnerability, it was already patched in the squareup/moshi library, just needs to tricke down to use
```
+--- com.netflix.nebula:nebula-project-plugin:latest.release -> 11.0.0
|    +--- com.netflix.nebula:nebula-gradle-interop:2.1.1 -> 2.3.0 (*)
|    +--- com.netflix.nebula:nebula-publishing-plugin:21.0.0 -> 21.1.0 (*)
|    +--- com.netflix.nebula:gradle-contacts-plugin:7.0.1
|    +--- com.netflix.nebula:gradle-dependency-lock-plugin:15.1.0
|    |    +--- com.squareup.moshi:moshi:1.12.0
|    |    |    +--- com.squareup.okio:okio:2.10.0
```
=> Add suppression

src/main/resources/suppressions.xml, suppressions.xml
This addresses the remaining highs in
- https://github.com/moderneinc/dependency-vulnerability-reports/issues/833
- https://github.com/moderneinc/dependency-vulnerability-reports/issues/835
and 
- https://github.com/moderneinc/dependency-vulnerability-reports/issues/834
- https://github.com/moderneinc/dependency-vulnerability-reports/issues/836
=> Update suppressions 

settings.gradle.kts
- resolves https://github.com/moderneinc/moderne-cli/issues/2473
=> Remove inclusion of non-existent `plugin` subproject

src/main/java/org/openrewrite/gradle/RecipeDependenciesTypeTableTask.java, src/main/java/org/openrewrite/gradle/RewriteLanguageLibraryPlugin.java, src/main/java/org/openrewrite/gradle/RewriteRecipeLibraryBasePlugin.java
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.recipes.rewrite.OpenRewriteRecipeBestPractices?organizationId=QUxML09wZW4gU291cmNlL09wZW5SZXdyaXRl
=> OpenRewrite recipe best practices
